language: python

# This is largely copied from PsychoPy's own travis config. The problem is that, because I am testing something that is
# effectively a psychopy add-on, I need all the dummy materials psychopy needs in order to successfully test.

matrix:
  include:

    - os: linux
      dist: trusty
      env: ANACONDA=false WXPYTHON=3 OPENPYXL=2.4 DISPLAY=:99.0 AUDIODEV=null

    - os: linux
      dist: trusty
      env: ANACONDA=false WXPYTHON=4 OPENPYXL=2.4 DISPLAY=:99.0 AUDIODEV=null

    - os: linux
      dist: trusty
      env: ANACONDA=false WXPYTHON=3 OPENPYXL=2.5 DISPLAY=:99.0 AUDIODEV=null

    - os: linux
      dist: trusty
      python: 3.6
      env: ANACONDA=false DISPLAY=:99.0 AUDIODEV=null


before_install:
  # System setup
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -qq lsb-release
  - source /etc/lsb-release
  - echo ${DISTRIB_CODENAME} # We need Trusty, specifically. Xenial is busted.
  - wget -O- http://neuro.debian.net/lists/${DISTRIB_CODENAME}.us-nh.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - wget -q -O- http://neuro.debian.net/_static/neuro.debian.net.asc | sudo apt-key add -
  - travis_retry sudo apt-get update -qq
  - sudo apt-cache policy  # What is actually available?

  # This might come in handy once we switch to Trusty, as its Xvfb
  # doesn't properly support the RANDR extension
  # - travis_retry sudo apt-get install -qq xpra xserver-xorg-video-dummy
  - travis_retry sudo apt-get install -qq xvfb xauth libgl1-mesa-dri libavbin0 # Fails. Xenial problem.
  - travis_retry sudo apt-get install -qq libportaudio2
  - travis_retry sudo apt-get install -qq flac
  - travis_retry sudo apt-get install -qq libav-tools  # this install ffmpeg
  - travis_retry sudo apt-get install -qq libwebkitgtk-1.0-0
  - flac -version
  # Trying to fix pyqt bug
  - travis_retry sudo apt-get install -qq python-qt4 #python-wxgtk3.0

  # Locales
  - travis_retry sudo apt-get install -qq language-pack-en-base  # English locales
  - travis_retry sudo apt-get install -qq language-pack-ja-base  # Japanese locale
  # - sudo dpkg-reconfigure locales
  # - locale -a  # list available locales

  - travis_retry sudo apt-get install -qq libasound2-dev alsa-utils alsa-oss
  - sudo modprobe snd-dummy # Broken
  - sudo lsmod


install:
  - pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04 wxPython
  - pip install -r requirements.txt

# Creates a fake monitor
before_script:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
       /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1024x768x24 -ac +extension GLX +extension RANDR +render -noreset;
    fi

script:
  - pytest